version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - PUBLIC_BACKEND_URL=http://localhost:8000
      - CLAMAV_URL=tcp://clamav:3310
    volumes:
      - ./backend:/app
      - /app/.venv # Ignore local virtual environment inside container
      - ./analyzers:/app/analyzers
      - ./workers:/app/workers
      - /var/run/docker.sock:/var/run/docker.sock
      - ./sandbox:/app/sandbox
    depends_on:
      - clamav
      - redis

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: rq worker scans --url redis://redis:6379/0
    env_file:
      - ./backend/.env
    environment:
      - CLAMAV_URL=tcp://clamav:3310
    volumes:
      - ./backend:/app
      - /app/.venv # Ignore local virtual environment inside container
      - ./analyzers:/app/analyzers
      - ./workers:/app/workers
      - /var/run/docker.sock:/var/run/docker.sock
      - ./sandbox:/app/sandbox
    depends_on:
      - clamav
      - redis

  redis:
    image: redis:7-alpine

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules # Ignore local node_modules
      - /app/.next # Ignore Next.js cache
    depends_on:
      - backend

  clamav:
    image: clamav/clamav:latest
    ports:
      - "3310:3310"
